server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://47.101.130.37:8000/eureka/,http://peer1:8000/eureka/,http://peer2:8002/eureka/,http://peer3:8003/eureka/
spring:
  application:
    name: cheng-lu
  datasource:
    url: jdbc:mysql://127.0.0.1/hzero_platform?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    inetutils:
      timeout-seconds: 10
  mail:
    host: smtp.qq.com
    username: 1107956939@qq.com
    password: vgqojlakamsuigcf
    default-encoding: UTF-8
    protocol: smtp
#    host: smtphm.qiye.163.com
#    username: lu.cheng01@hand-china.com
#    password: mQF97EwK5Ze3KLJC
#    default-encoding: UTF-8
#    protocol: smtp

mybatis:
  typeAliasesPackage: com.hzero.chenglu.entity
  mapperLocations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


---
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check