server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8002/eureka/,http://peer3:8003/eureka/
spring:
  application:
    name: gateway-service
  cloud:
    inetutils:
      timeout-seconds: 10
zuul:
  routes:
    cheng-lu:
      path: /chenglu/**
      serviceId: cheng-lu
      stripPrefix: true
    test2-service:
      path: /test/**
      serviceId: test2-service
      stripPrefix: false
ribbon:
  eager-load:
    enabled: true
    clients: ees-ent, ees-flight, ees-merchant, ees-msg, ees-mst, ees-pay, ees-sys, ees-tem, ees-workflow
